# Generated by Django 5.0.9 on 2024-09-08 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blog_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pages.blogpost'),
        ),
    ]
